name: edge_ml_dart
description: A library for using Edge-ML with Dart.
version: 0.0.2
repository: https://github.com/edge-ml/dart/tree/main

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
