name: edge_ml_dart
description: A library for using Edge-ML with Dart.
version: 0.0.3
repository: https://github.com/edge-ml/dart/tree/main

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0
  http: ^1.3.0
  open_file: ^3.5.10
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
