name: edge_ml_dart
description: A library for using Edge-ML with Dart.
version: 1.0.0

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
