name: Analyze and build on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  analyze_and_build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter analyze
      - run: (cd example && flutter build web --dart-define=BUILD_COMMIT=$(git
          rev-parse --short HEAD) --dart-define=BUILD_BRANCH=$(git rev-parse
          --abbrev-ref HEAD))
